version: '3'

services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: adminpass
    ports:
      - "5432:5432"
    networks:
      - creditcard-network

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - creditcard-network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - creditcard-network

networks:
  creditcard-network:
    driver: bridge